# Generated by Django 4.1 on 2023-12-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
