# Generated by Django 4.1 on 2023-11-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_comment'),
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogs'),
        ),
    ]
