# Generated by Django 4.1 on 2023-11-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0002_video_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='blog',
        ),
    ]
