# Generated by Django 4.1 on 2023-11-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0003_remove_video_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
