# Generated by Django 4.1 on 2023-10-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube Embed URL', null=True),
        ),
    ]
